version: "3.8"

services:
  adwireguard:
    container_name: dwg-agh-wg
    image: dwg-local:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      # - '53:53'         # AdGuardHome DNS Port
      - '80:80'         # Default Address AdGuardHome WebUI
      - '443:443'       # DNS-over-HTTPS
      - '51820:51820/udp' # WireGuard port
      - '51821:51821/tcp' # wg-easy webUI
    environment:
      - WG_HOST=MYHOST_IP
      - PASSWORD=openode
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.10.x
      - WG_DEFAULT_DNS=10.2.0.100
      - WG_MTU=1280
    volumes:
      - './work:/opt/adwireguard/work'
      - './conf:/opt/adwireguard/conf'
      - './wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      vpn_net:
        ipv4_address: 10.2.0.100

networks:
  vpn_net:
    ipam:
      config:
        - subnet: 10.2.0.0/24
